/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Instance = {
  instance: string;
  entity: string;
  type:
    | "generic_building"
    | "greatbuilding"
    | "main_building"
    | "military"
    | "street";
  x: Coordinate;
  y: Coordinate;
  width: Extent;
  height: Extent;
  xPresence: Presence;
  yPresence: Presence;
};
export type Coordinate = number;
export type Extent = number;
export type Presence = "explicit" | "omitted-zero";
export type Rectangle = {
  x: Coordinate;
  y: Coordinate;
  width: Extent;
  length: Extent;
  xPresence: Presence;
  yPresence: Presence;
};
export type Blocked = {
  xPresent: boolean;
  yPresent: boolean;
  x?: Coordinate;
  y?: Coordinate;
  meaning: "unresolved";
};

/**
 * Issue #48 geometry-only intermediate for the approved #24 source projection; not Canonical City Snapshot v1 or solver input.
 */
export interface CityGeometryDraft {
  schemaVersion: "0.1";
  sourceVariant: "foe24-source-v2";
  axisConvention: {
    unit: "city-grid-cell";
    xIncreases: "east";
    yIncreases: "south";
  };
  /**
   * @minItems 399
   * @maxItems 399
   */
  ordinaryInstances: Instance[];
  /**
   * @minItems 234
   * @maxItems 234
   */
  unlockedRectangles: Rectangle[];
  /**
   * @minItems 49
   * @maxItems 49
   */
  blockedRecords: Blocked[];
  excludedCounts: {
    friends_tavern: number;
    hub_main: number;
    hub_part: number;
    off_grid: number;
    outpost_ship: number;
  };
  counts: {
    sourceRecords: 419;
    ordinaryInstances: 399;
    unlockedRectangles: 234;
    roads: 124;
    excludedRecords: 20;
    availableCells: number;
    occupiedCells: number;
    freeCells: number;
  };
  /**
   * @minItems 3
   * @maxItems 3
   */
  diagnostics: (
    | "BLOCKED_MEANING_UNRESOLVED"
    | "ROAD_DEMAND_UNRESOLVED"
    | "SPECIAL_ELIGIBILITY_UNRESOLVED"
  )[];
}
